language: go

go:
  - 1.8.x
  - master

before_install:
  - go get github.com/tebben/overalls
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test ./...
  - overalls -project=github.com/geodan/gost -covermode=count -ignore=".git" -debug true
  - goveralls -coverprofile=/home/travis/gopath/src/github.com/geodan/gost/overalls.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN

notifications:
  email:
    recipients:
      - tim.ebben@geodan.nl
    on_success: change
    on_failure: always
